FROM openjdk:11
EXPOSE 8080:8080
RUN mkdir /app
COPY build/libs/*.jar /app/
ENTRYPOINT java -DDATABASE_HOST=${DATABASE_HOST} -DDATABASE_PORT=${DATABASE_PORT} -DDATABASE_NAME=${DATABASE_NAME} -DDATABASE_USER=${DATABASE_USER} -DDATABASE_PASSWORD=${DATABASE_PASSWORD} -jar /app/dev.daryl.ktor-todolist-all.jar