services:
  db:
    restart: always
    volumes:
      - /home/ubuntu/docker-volume/ktor-todolist-mysql-data:/var/lib/mysql
    networks:
      - traefik-proxy

  phpmyadmin:
    restart: always
    labels:
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.grad1e.ddns.net`)
    networks:
      - traefik-proxy

  api:
    restart: always
    labels:
      - traefik.http.routers.api.rule=(Host(`todo.grad1e.ddns.net`) && PathPrefix(`/api`))
    environment:
      DEVELOPMENT: false
    networks:
      - traefik-proxy


networks:
  traefik-proxy:
    external: true
    name: traefik_traefik-proxy