services:
  web:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: todo_app
      DATABASE_USER: root
      DATABASE_PASSWORD: grad1e
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: grad1e
      MYSQL_DATABASE: todo_app
    ports:
      - 3306:3306
    volumes:
      - /home/daryl/dev-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db